name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        name: Prepare repo
      - uses: actions/checkout@v2
        name: Set up Python 3.6.7
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6.7
        name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python manage.py test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "django-user" #Must be unique in Heroku
          heroku_email: "ronan.ripasy@gmail.com"
      - name: Successful Message
        run: echo Successfully Deployed!!